/**
 * One-shot generator: converts us-atlas pre-projected Albers TopoJSON
 * (states-albers-10m, 975x610 viewport) into a static TypeScript module of
 * SVG path strings, so the runtime map component needs zero geo dependencies.
 *
 *   node scripts/generate-us-map.mjs
 *
 * Re-run only if us-atlas is upgraded. Output: src/app/lib/us-map-data.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import * as topojson from "topojson-client";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const FIPS_TO_POSTAL = {
  "01": "AL", "02": "AK", "04": "AZ", "05": "AR", "06": "CA", "08": "CO",
  "09": "CT", "10": "DE", "11": "DC", "12": "FL", "13": "GA", "15": "HI",
  "16": "ID", "17": "IL", "18": "IN", "19": "IA", "20": "KS", "21": "KY",
  "22": "LA", "23": "ME", "24": "MD", "25": "MA", "26": "MI", "27": "MN",
  "28": "MS", "29": "MO", "30": "MT", "31": "NE", "32": "NV", "33": "NH",
  "34": "NJ", "35": "NM", "36": "NY", "37": "NC", "38": "ND", "39": "OH",
  "40": "OK", "41": "OR", "42": "PA", "44": "RI", "45": "SC", "46": "SD",
  "47": "TN", "48": "TX", "49": "UT", "50": "VT", "51": "VA", "53": "WA",
  "54": "WV", "55": "WI", "56": "WY",
};

const r1 = (n) => Math.round(n);

/** GeoJSON Polygon/MultiPolygon -> compact SVG path (coords already planar). */
function toPath(geometry) {
  const ring = (pts) =>
    pts.map(([x, y], i) => `${i === 0 ? "M" : "L"}${r1(x)},${r1(y)}`).join("") + "Z";
  if (geometry.type === "Polygon") return geometry.coordinates.map(ring).join("");
  if (geometry.type === "MultiPolygon")
    return geometry.coordinates.map((poly) => poly.map(ring).join("")).join("");
  throw new Error(`unsupported geometry: ${geometry.type}`);
}

/** Planar centroid of the largest ring (good enough for label anchors). */
function centroidOf(geometry) {
  const rings =
    geometry.type === "Polygon"
      ? [geometry.coordinates[0]]
      : geometry.coordinates.map((p) => p[0]);
  let best = rings[0];
  let bestArea = -1;
  for (const r of rings) {
    let a = 0;
    for (let i = 0; i < r.length - 1; i++) a += r[i][0] * r[i + 1][1] - r[i + 1][0] * r[i][1];
    a = Math.abs(a / 2);
    if (a > bestArea) { bestArea = a; best = r; }
  }
  let cx = 0, cy = 0, a = 0;
  for (let i = 0; i < best.length - 1; i++) {
    const cross = best[i][0] * best[i + 1][1] - best[i + 1][0] * best[i][1];
    a += cross;
    cx += (best[i][0] + best[i + 1][0]) * cross;
    cy += (best[i][1] + best[i + 1][1]) * cross;
  }
  a /= 2;
  return [Math.round(cx / (6 * a)), Math.round(cy / (6 * a))];
}

const statesTopo = JSON.parse(
  readFileSync(join(root, "node_modules/us-atlas/states-albers-10m.json"), "utf8"),
);
const nationTopo = JSON.parse(
  readFileSync(join(root, "node_modules/us-atlas/nation-albers-10m.json"), "utf8"),
);

const states = topojson.feature(statesTopo, statesTopo.objects.states).features;
const nation = topojson.feature(nationTopo, nationTopo.objects.nation).features[0];

const rows = states
  .filter((f) => FIPS_TO_POSTAL[f.id])
  .map((f) => {
    const [cx, cy] = centroidOf(f.geometry);
    return {
      postal: FIPS_TO_POSTAL[f.id],
      name: f.properties.name,
      cx,
      cy,
      d: toPath(f.geometry),
    };
  })
  .sort((a, b) => a.postal.localeCompare(b.postal));

const ts = `/**
 * GENERATED by scripts/generate-us-map.mjs from us-atlas states-albers-10m
 * (ISC, US Census Bureau geography, public domain). Pre-projected Albers USA,
 * 975x610 viewport. Do not edit by hand - re-run the script instead.
 */

export const US_MAP_VIEWBOX = "0 0 975 610";

export interface StatePath {
  /** USPS postal code, uppercase ("CA"). */
  postal: string;
  name: string;
  /** Planar label centroid in viewBox coordinates. */
  cx: number;
  cy: number;
  /** SVG path data (Albers USA projected). */
  d: string;
}

export const NATION_PATH = ${JSON.stringify(toPath(nation.geometry))};

export const STATE_PATHS: StatePath[] = ${JSON.stringify(rows, null, 0)};
`;

writeFileSync(join(root, "src/app/lib/us-map-data.ts"), ts);
console.log(
  `wrote src/app/lib/us-map-data.ts: ${rows.length} states, ${(ts.length / 1024).toFixed(0)} KB`,
);
